// ===========================================================================
// Slate — production wiring. {{COUNT}} icons, "{{STYLE}}" style.
// Generated by tools/build_slate.py.
//
// Icon artwork: Google Material Design Icons, Apache License 2.0. See NOTICE.md.
//
// Paste the whole file into App.Formulas (Tree view -> App -> Formulas).
//
// Why App.Formulas and not App.OnStart:
//   * Named formulas are evaluated lazily and cached, so the icon table costs
//     nothing until an icon is actually drawn, and nothing at all on app open.
//     A 100+ row ClearCollect in OnStart is pure added launch latency.
//   * They are immutable, so no screen can accidentally Clear() your icon set.
//
// The Slate_* user-defined functions need "User-defined functions" switched on
// under Settings -> Updates -> New. If your tenant does not have that toggle
// yet (common on GCC / GCC High), delete the UDF block and use the inline
// pattern documented in docs/HOW-IT-WORKS.md instead — the named formula
// SlateIcons works either way.
// ===========================================================================

// --------------------------------------------------------------- icon table
SlateIcons =
    Table(
{{ICON_ROWS}}
    );

// ------------------------------------------------------------- theme colour
// Point this at your own theme. Everything below inherits it.
SlateDefaultColor = RGBA(31, 56, 100, 1);   // #1F3864


// ============================ user-defined functions =======================
// Requires the "User-defined functions" preview toggle.

// Wrap raw 24x24 path data into a renderable data URI.
// Left(RGBAToHex(c), 7) drops the alpha pair: Power Apps' SVG renderer wants
// #RRGGBB, and an 8-digit hex silently renders as black.
Slate_UriFromPath(path: Text, fill: Color): Text =
    "data:image/svg+xml;utf8," &
    EncodeUrl(
        "<svg xmlns=""http://www.w3.org/2000/svg"" viewBox=""0 0 24 24"" fill=""" &
        Left(RGBAToHex(fill), 7) &
        """><path d=""" & path & """/></svg>"
    );

// Look an icon up by its Material name and return the data URI.
// Blank name or unknown name yields a blank image rather than a broken one.
Slate_Icon(name: Text, fill: Color): Text =
    With(
        { p: LookUp(SlateIcons, Name = name).Path },
        If(IsBlank(p), "", Slate_UriFromPath(p, fill))
    );

// Same, in the app's default colour.
Slate_IconDefault(name: Text): Text =
    Slate_Icon(name, SlateDefaultColor);


// ================================== usage ==================================
//
//   Image control:
//       Image:          =Slate_Icon("shield", RGBA(16, 124, 16, 1))
//       ImagePosition:  =ImagePosition.Fit
//
//   Icon button that reacts to state:
//       Image: =Slate_Icon(
//                  If(locSaving, "hourglass_empty", "save"),
//                  If(Self.Pressed, RGBA(255,255,255,1), SlateDefaultColor)
//              )
//
//   Gallery row status glyph:
//       Image: =Slate_Icon(
//                  Switch(ThisItem.Status,
//                      "Approved", "check_circle",
//                      "Rejected", "cancel",
//                      "pending"),
//                  Switch(ThisItem.Status,
//                      "Approved", RGBA(16,124,16,1),
//                      "Rejected", RGBA(164,38,44,1),
//                      RGBA(96,94,92,1))
//              )
//
//   No UDFs available? Inline the wrapper instead:
//       Image: ="data:image/svg+xml;utf8," & EncodeUrl(
//                   "<svg xmlns=""http://www.w3.org/2000/svg"" viewBox=""0 0 24 24"" fill=""#1F3864""><path d=""" &
//                   LookUp(SlateIcons, Name = "shield").Path & """/></svg>"
//               )
// ===========================================================================
