# ---------------------------------------------------------------------------
# Slate — Material Design icons as inline SVG for Power Apps
# {{COUNT}} icons, "{{STYLE}}" style. Generated by tools/build_slate.py.
#
# Icon artwork: Google Material Design Icons, Apache License 2.0. See NOTICE.md.
#
# HOW TO USE
#   Power Apps Studio -> Tree view -> click "..." on App -> Paste (or Ctrl+V on
#   the canvas with this file's contents on your clipboard).
#   If Studio rejects this file, use src/slate-icon-browser.clipboard.yaml
#   instead: add a blank screen first, then paste the controls onto it and copy
#   src/slate-screen-onvisible.fx into that screen's OnVisible.
#
# NO NETWORK CALLS. Every icon is a data URI built at runtime from path data
# held in the app, so this works on a locked-down GCC / GCC High tenant with no
# CDN allowlist, no media files, and no connector.
# ---------------------------------------------------------------------------
Screens:
  scrSlateIcons:
    Properties:
      Fill: =RGBA(247, 248, 250, 1)
      OnVisible: |
        =/* --------------------------------------------------------------
           Slate icon table. Path data is the `d` attribute of the Material
           24x24 source SVG. In production, move this to App.Formulas as a
           named formula (see src/slate-app-formulas.fx) so it is evaluated
           once, app-wide, instead of on every screen visit.
           -------------------------------------------------------------- */
        ClearCollect(
            colSlateIcons,
            Table(
{{ICON_ROWS}}
            )
        );
        Set(gblSlateBrandPath, LookUp(colSlateIcons, Name = "grid_view").Path);
    Children:
      # ------------------------------------------------------------ header
      - recSlateHeader:
          Control: Rectangle
          Properties:
            X: =0
            Y: =0
            Width: =Parent.Width
            Height: =64
            Fill: =RGBA(31, 56, 100, 1)

      - imgSlateBrand:
          Control: Image
          Properties:
            X: =24
            Y: =16
            Width: =32
            Height: =32
            ImagePosition: =ImagePosition.Fit
            Image: |
              ="data:image/svg+xml;utf8," & EncodeUrl(
                  "<svg xmlns=""http://www.w3.org/2000/svg"" viewBox=""0 0 24 24"" fill=""#FFFFFF""><path d=""" &
                  Coalesce(gblSlateBrandPath, "M3 3h8v8H3zm10 0h8v8h-8zM3 13h8v8H3zm10 0h8v8h-8z") &
                  """/></svg>"
              )

      - lblSlateTitle:
          Control: Label
          Properties:
            X: =68
            Y: =12
            Width: =520
            Height: =24
            Text: ="Slate"
            Color: =RGBA(255, 255, 255, 1)
            Size: =15
            FontWeight: =FontWeight.Semibold
            VerticalAlign: =VerticalAlign.Middle

      - lblSlateSubtitle:
          Control: Label
          Properties:
            X: =68
            Y: =34
            Width: =520
            Height: =20
            Text: ="Material Design icons as inline SVG — no CDN, no media files, GCC safe"
            Color: =RGBA(255, 255, 255, 0.72)
            Size: =9
            VerticalAlign: =VerticalAlign.Middle

      - lblSlateCount:
          Control: Label
          Properties:
            X: =Parent.Width - Self.Width - 24
            Y: =20
            Width: =260
            Height: =24
            Text: |
              =CountRows(galSlateIcons.AllItems) & " of " & CountRows(colSlateIcons) & " icons"
            Color: =RGBA(255, 255, 255, 0.72)
            Size: =10
            Align: =Align.Right
            VerticalAlign: =VerticalAlign.Middle

      # ----------------------------------------------------------- toolbar
      - txtSlateSearch:
          Control: Classic/TextInput
          Properties:
            X: =24
            Y: =80
            Width: =360
            Height: =40
            Default: =""
            HintText: ="Search by name, category or keyword"
            Clear: =true
            Size: =11
            BorderColor: =RGBA(200, 204, 210, 1)

      - drpSlateCat:
          Control: Classic/DropDown
          Properties:
            X: =396
            Y: =80
            Width: =180
            Height: =40
            Items: =["All", {{CATEGORIES}}]
            Default: ="All"
            Size: =11

      - drpSlateColor:
          Control: Classic/DropDown
          Properties:
            X: =588
            Y: =80
            Width: =150
            Height: =40
            Items: |
              =["#1F3864", "#0F6CBD", "#0B6A6A", "#107C10", "#A4262C", "#8A3FFC", "#605E5C", "#201F1E"]
            Default: ="#1F3864"
            Size: =11

      - drpSlateSize:
          Control: Classic/DropDown
          Properties:
            X: =750
            Y: =80
            Width: =110
            Height: =40
            Items: =["16", "20", "24", "32", "40", "48", "64"]
            Default: ="40"
            Size: =11

      # ------------------------------------------------------------- grid
      - galSlateIcons:
          Control: Gallery
          Variant: BrowseLayout_Vertical_TwoTextOneImage_VariantA_ver5.0
          Properties:
            X: =24
            Y: =136
            Width: =816
            Height: =Parent.Height - 160
            Layout: =Layout.Vertical
            WrapCount: =5
            TemplateSize: =124
            TemplatePadding: =0
            ShowScrollbar: =true
            Items: |
              =With(
                  {
                      q: Trim(txtSlateSearch.Value),
                      c: drpSlateCat.Selected.Value
                  },
                  Filter(
                      colSlateIcons,
                      (c = "All" || ThisRecord.Cat = c) &&
                      (
                          IsBlank(q) ||
                          q in ThisRecord.Name ||
                          q in ThisRecord.Title ||
                          q in ThisRecord.Tags
                      )
                  )
              )
          Children:
            - recSlateCell:
                Control: Rectangle
                Properties:
                  X: =4
                  Y: =4
                  Width: =Parent.TemplateWidth - 8
                  Height: =Parent.TemplateHeight - 8
                  Fill: |
                    =If(
                        ThisItem.IsSelected,
                        ColorFade(ColorValue(drpSlateColor.Selected.Value), 0.9),
                        RGBA(255, 255, 255, 1)
                    )
                  BorderColor: |
                    =If(
                        ThisItem.IsSelected,
                        ColorValue(drpSlateColor.Selected.Value),
                        RGBA(225, 228, 232, 1)
                    )
                  BorderThickness: =1

            - imgSlateIcon:
                Control: Image
                Properties:
                  Width: =Value(drpSlateSize.Selected.Value)
                  Height: =Self.Width
                  X: =(Parent.TemplateWidth - Self.Width) / 2
                  Y: =16
                  ImagePosition: =ImagePosition.Fit
                  # ---- THIS IS THE WHOLE TRICK ----------------------------
                  # A data URI is the only image source Power Apps will render
                  # from a formula. ";utf8," (not ";charset=utf-8,") and the
                  # explicit xmlns are both mandatory or you get a blank box.
                  # EncodeUrl escapes the markup; the fill colour must be a
                  # 6-digit hex, hence Left(RGBAToHex(...), 7).
                  Image: |
                    ="data:image/svg+xml;utf8," & EncodeUrl(
                        "<svg xmlns=""http://www.w3.org/2000/svg"" viewBox=""0 0 24 24"" fill=""" &
                        Left(RGBAToHex(ColorValue(drpSlateColor.Selected.Value)), 7) &
                        """><path d=""" & ThisItem.Path & """/></svg>"
                    )

            - lblSlateCellName:
                Control: Label
                Properties:
                  X: =8
                  Y: =Parent.TemplateHeight - 48
                  Width: =Parent.TemplateWidth - 16
                  Height: =36
                  Text: =ThisItem.Name
                  Size: =8
                  Align: =Align.Center
                  VerticalAlign: =VerticalAlign.Top
                  Color: =RGBA(70, 74, 80, 1)
                  Wrap: =true

      # ---------------------------------------------------------- detail
      - recSlateDetail:
          Control: Rectangle
          Properties:
            X: =864
            Y: =136
            Width: =Parent.Width - 888
            Height: =Parent.Height - 160
            Fill: =RGBA(255, 255, 255, 1)
            BorderColor: =RGBA(225, 228, 232, 1)
            BorderThickness: =1

      - imgSlateDetailIcon:
          Control: Image
          Properties:
            X: =recSlateDetail.X + 24
            Y: =recSlateDetail.Y + 24
            Width: =96
            Height: =96
            ImagePosition: =ImagePosition.Fit
            Image: |
              =If(
                  IsBlank(galSlateIcons.Selected),
                  Blank(),
                  "data:image/svg+xml;utf8," & EncodeUrl(
                      "<svg xmlns=""http://www.w3.org/2000/svg"" viewBox=""0 0 24 24"" fill=""" &
                      Left(RGBAToHex(ColorValue(drpSlateColor.Selected.Value)), 7) &
                      """><path d=""" & galSlateIcons.Selected.Path & """/></svg>"
                  )
              )

      - lblSlateDetailTitle:
          Control: Label
          Properties:
            X: =recSlateDetail.X + 136
            Y: =recSlateDetail.Y + 30
            Width: =recSlateDetail.Width - 160
            Height: =32
            Text: =Coalesce(galSlateIcons.Selected.Title, "Select an icon")
            Size: =16
            FontWeight: =FontWeight.Semibold
            Color: =RGBA(32, 31, 30, 1)

      - lblSlateDetailMeta:
          Control: Label
          Properties:
            X: =recSlateDetail.X + 136
            Y: =recSlateDetail.Y + 64
            Width: =recSlateDetail.Width - 160
            Height: =44
            Text: |
              =If(
                  IsBlank(galSlateIcons.Selected),
                  "Pick any icon on the left to get its ready-to-paste Power Fx.",
                  galSlateIcons.Selected.Name & Char(10) & galSlateIcons.Selected.Cat
              )
            Size: =10
            Color: =RGBA(96, 94, 92, 1)
            Wrap: =true

      - lblSlateSnippetCaption:
          Control: Label
          Properties:
            X: =recSlateDetail.X + 24
            Y: =recSlateDetail.Y + 144
            Width: =recSlateDetail.Width - 48
            Height: =24
            Text: ="Image property — select all, copy, paste"
            Size: =10
            FontWeight: =FontWeight.Semibold
            Color: =RGBA(70, 74, 80, 1)

      - txtSlateSnippet:
          Control: Classic/TextInput
          Properties:
            X: =recSlateDetail.X + 24
            Y: =recSlateDetail.Y + 172
            Width: =recSlateDetail.Width - 48
            Height: =260
            Mode: =TextMode.MultiLine
            Size: =9
            Font: =Font.'Courier New'
            BorderColor: =RGBA(225, 228, 232, 1)
            Fill: =RGBA(250, 250, 251, 1)
            # Rebuilds the exact one-liner a developer needs. Char(34) is a
            # double quote; two of them produce the "" escape Power Fx wants
            # inside a string literal.
            Default: |
              =With(
                  {
                      q: Char(34),
                      qq: Char(34) & Char(34),
                      p: Coalesce(galSlateIcons.Selected.Path, "")
                  },
                  If(
                      IsBlank(galSlateIcons.Selected),
                      "",
                      q & "data:image/svg+xml;utf8," & q & " & EncodeUrl(" & q &
                      "<svg xmlns=" & qq & "http://www.w3.org/2000/svg" & qq &
                      " viewBox=" & qq & "0 0 24 24" & qq &
                      " fill=" & qq & drpSlateColor.Selected.Value & qq & ">" &
                      "<path d=" & qq & p & qq & "/></svg>" & q & ")"
                  )
              )

      - lblSlateFootnote:
          Control: Label
          Properties:
            X: =recSlateDetail.X + 24
            Y: =recSlateDetail.Y + 444
            Width: =recSlateDetail.Width - 48
            Height: =96
            Text: |
              ="Set the host Image control's ImagePosition to Fit — the SVG has no fixed size, so it scales to whatever Width and Height you give it. Swap the fill hex for Left(RGBAToHex(YourTheme.Primary), 7) to bind it to a theme."
            Size: =9
            Color: =RGBA(96, 94, 92, 1)
            Wrap: =true
